### ISSUE TITLE
DELETE /organizer/{id}

### ISSUE THREAD

**Issue by Xevi8X** [IO2-Team/Backend#13]
Można usunąc kogokolwiek

**Comment by Xevi8X** [comment]
https://github.com/IO2-Team/Backend/blob/80343cb09addf58689c3379c746f8d92112076be/Backend/Controllers/EventOrganizerApi.cs#L101

Należy użyć tego id i porównać go z organizatorem przed usunieciem

**Comment by kutakw** [comment]
Done :))
